### ISSUE TITLE
cannot configure hdfs to use non-native hadoop binaries

### ISSUE THREAD

**Issue by ryane** [mesosphere/dcos-hdfs#5]
I am installing hdfs with a custom mesos-site.xml file that has `mesos.hdfs.native-hadoop-binaries` set to false.

```xml
  <property>
    <name>mesos.hdfs.native-hadoop-binaries</name>
    <description>Mark true if you have hadoop pre-installed on your host machines (otherwise it will be distributed by the scheduler)</description>
    <value>false</value>
  </property>
```

I use `config-gen` to generate an options.json file that will include my custom mesos-site.xml (note that I am using a patched version that includes the fix in https://github.com/mesosphere/dcos-hdfs/pull/4) and install hdfs with:

```bash
dcos package install hdfs --options=options.json --yes
```

The mesos-site.xml is correctly copied to ./etc/hadoop when the scheduler launches. However, the package that is distributed to the slaves does not include the customized mesos-site.xml and `mesos.hdfs.native-hadoop-binaries` remains true. Therefore, the hadoop binaries are never distributed to the slaves.

**Comment by elingg** [comment]
I commented on this issue in mesosphere/hdfs, https://github.com/mesosphere/hdfs/issues/155. That is the correct location for this issue since this repo is for the HDFS CLI only.
