### ISSUE TITLE
hdfs service unable to start: Error: Could not find or load main class org.apache.mesos.hdfs.scheduler.Main

### ISSUE THREAD

**Issue by besil** [mesosphere/dcos-hdfs#6]
Hi,

We are experiencing an error while installing the hdfs service on our mesos service.
The issue started today, until yesterday it worked cleanly.

This is the stderr of the failed task:
```
I0825 08:03:04.968940  1377 exec.cpp:206] Executor registered on slave 20150825-075527-1543831562-5050-1273-S0
Error: Could not find or load main class org.apache.mesos.hdfs.scheduler.Main
15/08/25 08:03:05 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
-ls: java.net.UnknownHostException: hdfs
Usage: hadoop fs [generic options] -ls [-d] [-h] [-R] [<path> ...]
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0825 08:03:05.792335  1389 main.cpp:99] Ignoring failure as health check still in grace period
```

The hdfs service keeps failing and restarting along with this message.
We noticed that the service is not registered to the exhibitor service.

Other services like spark or chronos work as expected.

**Comment by besil** [comment]
Issue was closed yesterday by the hdfs team.

**Comment by BhavnaChoubey** [comment]
I am also facing the same issue.I tried the same steps mentioned in URL https://github.com/mesosphere/hdfs but on running ./bin/hdfs-mesos getting error as :
Error: Could not find or load main class org.apache.mesos.hdfs.scheduler.Main
Please let me know as what can be done ?

**Comment by jomach** [comment]
+1
