### ISSUE TITLE
HDFS datanodes not showing up

### ISSUE THREAD

**Issue by anubhavsinha** [mesosphere/dcos-hdfs#7]
Hi,

When I setup a fresh mesos cluster through mesosphere aws template ( from the mesosphere website),
I am able to deploy hdfs first time correctly. Everything works.
I used 
dcos package install hdfs
When I uninstall hdfs using 
dcos package uninstall hdfs and again try to install it,
one of the datanodes(total was 3) doesn't show up in the namenode web ui. 
Again after uninstalling and then installing..now 2 of them don't show up.
And if I repeat it once more.. All 3 are gone.

I am cleaning the Zookeeper entries as recommended every time after uninstalling hdfs.
Any pointers to fix this be highly appreciated.

**Comment by yogeshnath** [comment]
I'm having a similar issue. After uninstalling a new times, both datanodes and namenodes don't show up. I get an exception that namenode1.hdfs.mesos could not be resolved, and install process gets killed. I don't see that entry in mesos-dns.
